# Generated by Django 3.1.7 on 2021-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=100)),
                ('med_price', models.ImageField(upload_to='')),
                ('med_img', models.ImageField(upload_to='pictures')),
                ('med_sale', models.BooleanField(default=False)),
                ('med_des', models.TextField()),
            ],
        ),
    ]
