# Generated by Django 3.1.7 on 2021-03-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_products',
            name='med_price',
            field=models.IntegerField(),
        ),
    ]
