# Generated by Django 3.1.6 on 2021-03-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0002_auto_20210311_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_products',
            name='med_category',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medical_products',
            name='med_type',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
