# Generated by Django 3.1.7 on 2021-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0004_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_reviews',
            name='one_word_review',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
