# Generated by Django 3.1.7 on 2021-04-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0005_product_reviews_one_word_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_reviews',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
