# Generated by Django 2.1 on 2021-05-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0009_auto_20210504_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
    ]
