# Generated by Django 2.1 on 2021-05-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0010_remove_payment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_paymentid',
            new_name='razorpay_payment_id',
        ),
    ]
