# Generated by Django 2.1 on 2021-05-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0012_auto_20210504_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
